import { z } from 'zod'

const detailSchema = z.object({
	bvid: z.string(),
	aid: z.number(),
	videos: z.number(),
	tid: z.number(),
	tid_v2: z.number(),
	tname: z.string(),
	tname_v2: z.string(),
	copyright: z.number(),
	pic: z.string(),
	title: z.string(),
	pubdate: z.number(),
	ctime: z.number(),
	desc: z.string(),
	desc_v2: z.array(
		z.object({ raw_text: z.string(), type: z.number(), biz_id: z.number() }),
	),
	state: z.number(),
	duration: z.number(),
	mission_id: z.number(),
	rights: z.object({
		bp: z.number(),
		elec: z.number(),
		download: z.number(),
		movie: z.number(),
		pay: z.number(),
		hd5: z.number(),
		no_reprint: z.number(),
		autoplay: z.number(),
		ugc_pay: z.number(),
		is_cooperation: z.number(),
		ugc_pay_preview: z.number(),
		no_background: z.number(),
		clean_mode: z.number(),
		is_stein_gate: z.number(),
		is_360: z.number(),
		no_share: z.number(),
		arc_pay: z.number(),
		free_watch: z.number(),
	}),
	owner: z.object({ mid: z.number(), name: z.string(), face: z.string() }),
	stat: z.object({
		aid: z.number(),
		view: z.number(),
		danmaku: z.number(),
		reply: z.number(),
		favorite: z.number(),
		coin: z.number(),
		share: z.number(),
		now_rank: z.number(),
		his_rank: z.number(),
		like: z.number(),
		dislike: z.number(),
		evaluation: z.string(),
		vt: z.number(),
	}),
	argue_info: z.object({
		argue_msg: z.string(),
		argue_type: z.number(),
		argue_link: z.string(),
	}),
	dynamic: z.string(),
	cid: z.number(),
	dimension: z.object({
		width: z.number(),
		height: z.number(),
		rotate: z.number(),
	}),
	premiere: z.null(),
	teenage_mode: z.number(),
	is_chargeable_season: z.boolean(),
	is_story: z.boolean(),
	is_upower_exclusive: z.boolean(),
	is_upower_play: z.boolean(),
	is_upower_preview: z.boolean(),
	enable_vt: z.number(),
	vt_display: z.string(),
	is_upower_exclusive_with_qa: z.boolean(),
	no_cache: z.boolean(),
	pages: z.array(
		z.object({
			cid: z.number(),
			page: z.number(),
			from: z.string(),
			part: z.string(),
			duration: z.number(),
			vid: z.string(),
			weblink: z.string(),
			dimension: z.object({
				width: z.number(),
				height: z.number(),
				rotate: z.number(),
			}),
			first_frame: z.string(),
			ctime: z.number(),
		}),
	),
	subtitle: z.object({
		allow_submit: z.boolean(),
		list: z.array(z.unknown()),
	}),
	label: z.object({ type: z.number() }),
	is_season_display: z.boolean(),
	user_garb: z.object({ url_image_ani_cut: z.string() }),
	honor_reply: z.object({
		honor: z.array(
			z.object({
				aid: z.number(),
				type: z.number(),
				desc: z.string(),
				weekly_recommend_num: z.number(),
			}),
		),
	}),
	like_icon: z.string(),
	need_jump_bv: z.boolean(),
	disable_show_up_info: z.boolean(),
	is_story_play: z.number(),
	is_view_self: z.boolean(),
})

export const getVideoDetailSchema = z.object({
	code: z.number().optional(),
	message: z.string().optional(),
	ttl: z.number().optional(),
	data: detailSchema,
})
